[package]
name = "edgemorph_derive"
version = "0.1.0"
authors = ["David Golembiowski <david@dgolembiowski.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "1.0.41"
quote = "1.0.7"
proc-macro2 = "1.0.21"
